# Generated by Django 5.2.7 on 2025-11-09 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_question_quiz_option_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='quiz.quiz'),
        ),
    ]
