# Generated by Django 5.2.7 on 2025-11-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_plan_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='page_en',
            new_name='page',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='page_bn',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='title_bn',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='title_en',
        ),
        migrations.AddField(
            model_name='instruction',
            name='type',
            field=models.CharField(blank=True, null=True, verbose_name=[('instruction', 'Instruction'), ('time', 'Time')]),
        ),
        migrations.AddField(
            model_name='quiz',
            name='instruction',
            field=models.ManyToManyField(blank=True, to='quiz.instruction'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
