# Generated by Django 5.2.7 on 2025-11-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_rename_page_en_instruction_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='title_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='type',
            field=models.CharField(blank=True, choices=[('instruction', 'Instruction'), ('time', 'Time')], max_length=50, null=True),
        ),
    ]
