# Generated by Django 5.2.7 on 2025-11-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_instruction_title_bn_instruction_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='title_bn',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='title_en',
        ),
        migrations.AlterField(
            model_name='instruction',
            name='type',
            field=models.CharField(blank=True, null=True, verbose_name=[('instruction', 'Instruction'), ('time', 'Time')]),
        ),
    ]
