# Generated by Django 5.2.7 on 2025-11-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_remove_instruction_title_bn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='type',
            field=models.CharField(blank=True, null=True, verbose_name=[('instruction', 'Instruction'), ('time', 'Time'), ('error', 'Error')]),
        ),
    ]
