# Generated by Django 5.2.7 on 2025-11-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_instruction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='type',
        ),
        migrations.AddField(
            model_name='instruction',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
