# Generated by Django 5.2.7 on 2025-11-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_remove_instruction_type_instruction_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='title',
            new_name='title_en',
        ),
    ]
