# Generated by Django 5.2.7 on 2025-11-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_rename_title_instruction_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='contents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
