# Generated by Django 5.2.7 on 2025-11-10 14:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_instruction_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='contents',
        ),
        migrations.AddField(
            model_name='instruction',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
