# Generated by Django 5.2.7 on 2025-11-10 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_remove_instruction_contents_instruction_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='instruction',
        ),
        migrations.AddField(
            model_name='instruction',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='quiz.quiz'),
        ),
    ]
