# Generated by Django 5.2.7 on 2025-11-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_remove_quiz_instruction_instruction_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='instruction',
            field=models.ManyToManyField(blank=True, to='quiz.instruction'),
        ),
    ]
