# Generated by Django 5.2.7 on 2025-11-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_remove_instruction_quiz_quiz_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='quizzes',
            field=models.ManyToManyField(blank=True, related_name='plans', to='quiz.quiz'),
        ),
    ]
