# Generated by Django 5.2.7 on 2025-11-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_plan_quizzes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='total_questions',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
