# Generated by Django 5.2.7 on 2025-11-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_alter_quiz_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='can_see_explanation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='instant_feedback',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
