# Generated by Django 5.2.7 on 2025-11-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_quiz_can_see_explanation_quiz_instant_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='year',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
