# Generated by Django 5.2.7 on 2025-11-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_plan_month_plan_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='quizzes',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
