# Generated by Django 5.2.7 on 2025-11-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_remove_plan_quizzes_delete_feature_delete_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='assets/uploads/'),
        ),
    ]
