# Generated by Django 5.2.7 on 2025-11-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='month',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
