# Generated by Django 5.2.7 on 2025-11-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_usersubscription_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='monthly_discount',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='yearly_discount',
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='plan',
            name='yearly_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
