# Generated by Django 5.2.7 on 2025-11-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_usersubscription_monthly_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='button_variant',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='color',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='icon',
        ),
        migrations.AddField(
            model_name='plan',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
