# Generated by Django 5.2.7 on 2025-11-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_rename_name_plan_title_remove_plan_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='discount_type',
        ),
    ]
