# Generated by Django 5.2.7 on 2025-11-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_remove_plan_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='monthly_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='yearly_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
