# Generated by Django 5.2.7 on 2025-11-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_plan_monthly_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='discount_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
