# Generated by Django 5.2.7 on 2025-11-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_plan_discount_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='discount_type',
            new_name='choice',
        ),
    ]
