# Generated by Django 5.2.7 on 2025-11-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_rename_discount_type_plan_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='monthly_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='yearly_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
